---

- include: repo.yml

- name: Log in to Jenkins CLI if auth config is available
  # OK to ignore errors as it won't work before Jenkins is installed
  ignore_errors: yes
  command: >
    {{ jenkins_cli_cmd }} login --username {{ jenkins_admin_user }} --password {{ jenkins_admin_password }}
  when: jenkins_admin_user is defined and jenkins_admin_password is defined

- include: dependencies.yml

- name: Install Jenkins
  apt: name=jenkins state=latest
  register: jenkins_install

- include: config.yml

- include: cli.yml

- include: plugins.yml
