---
jenkins_dest: /opt/jenkins
jenkins_lib: /var/lib/jenkins
jenkins:
  repo: 'deb http://pkg.jenkins.io/debian-stable binary/' 
  dependencies: 
      - '{{ java_version }}-jre'
      - '{{ java_version }}-jdk'
      - 'git'
      - 'curl'
  cli_dest: 
      - '{{ jenkins_dest }}/jenkins-cli.jar' 
  updates_dest: 
      - '{{ jenkins_dest }}/updates_jenkins.json' 
jenkins_api_url: "http://localhost:{{ port }}{{ prefix }}"
jenkins_cli_cmd: "java -jar {{ jenkins.cli_dest }} -s {{ jenkins_api_url }}"